# Generated by Django 5.1.4 on 2024-12-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('sizes', models.JSONField()),
                ('brand', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
    ]
