# Generated by Django 5.1.4 on 2024-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.IntegerField(choices=[(4, 'Size 4'), (5, 'Size 5'), (6, 'Size 6'), (7, 'Size 7'), (8, 'Size 8')]),
        ),
    ]
