# Generated by Django 5.1.4 on 2024-12-26 06:27

from django.db import migrations, models

def convert_sizes_to_text(apps, schema_editor):
    """Convert integer to text."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE api_product
            ALTER COLUMN sizes TYPE TEXT USING sizes::TEXT;
        """)

def convert_sizes_to_jsonb(apps, schema_editor):
    """Convert text to JSONB."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE api_product
            SET sizes = jsonb_build_array(sizes::INTEGER)
            WHERE sizes IS NOT NULL;
        """)
        cursor.execute("""
            ALTER TABLE api_product
            ALTER COLUMN sizes TYPE JSONB USING sizes::JSONB;
        """)

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_sizes_to_text),
        migrations.RunPython(convert_sizes_to_jsonb),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(),
        ),
    ]


