# Generated by Django 5.1.4 on 2025-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
